# Generated by Django 2.2.17 on 2021-01-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0002_auto_20210122_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='user_group', to='course.Group'),
        ),
    ]
